# head
menu:
  主页: /
  文章: /archives
rss: /atom.xml
favicon: /favicon.png

# main
date_format: 'MMMM D, YYYY'
excerpt_link: READ MORE
comment_link: 0 COMMENTS

# foot
# themes_mata: ' ❤ Theme by <a href="http://unmric.com" target="_blank">unmric</a>'
google_analytics:
